// <auto-generated />
using System;
using DataPresenter.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataPresenter.Server.Migrations
{
    [DbContext(typeof(DataPresenterDbContext))]
    partial class DataPresenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataPresenter.Server.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 1,
                            SeriesId = 1,
                            Timestamp = new DateTime(2024, 11, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            Value = 22.399999999999999
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 1,
                            SeriesId = 1,
                            Timestamp = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            Value = 23.100000000000001
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 1,
                            SeriesId = 1,
                            Timestamp = new DateTime(2024, 11, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3,
                            Value = 24.5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 2,
                            SeriesId = 2,
                            Timestamp = new DateTime(2024, 11, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            Value = 48.299999999999997
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 2,
                            SeriesId = 2,
                            Timestamp = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 51.799999999999997
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 2,
                            SeriesId = 2,
                            Timestamp = new DateTime(2024, 11, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3,
                            Value = 55.200000000000003
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 3,
                            SeriesId = 3,
                            Timestamp = new DateTime(2024, 11, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 1013.2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 3,
                            SeriesId = 3,
                            Timestamp = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            Value = 1011.7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 3,
                            SeriesId = 3,
                            Timestamp = new DateTime(2024, 11, 2, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3,
                            Value = 1008.5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 4,
                            SeriesId = 4,
                            Timestamp = new DateTime(2024, 11, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 320.0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 4,
                            SeriesId = 4,
                            Timestamp = new DateTime(2024, 11, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 750.0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 4,
                            SeriesId = 4,
                            Timestamp = new DateTime(2024, 11, 1, 22, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 50.0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 5,
                            SeriesId = 5,
                            Timestamp = new DateTime(2024, 11, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 420.0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 5,
                            SeriesId = 5,
                            Timestamp = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Value = 780.0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SensorId = 5,
                            SeriesId = 5,
                            Timestamp = new DateTime(2024, 11, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3,
                            Value = 610.0
                        });
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDataReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("SeriesId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "TEMP_SALON_KEY",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Czujnik DHT22 w salonie",
                            IsActive = true,
                            Name = "Sensor temperatury - Salon",
                            SeriesId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApiKey = "HUM_SALON_KEY",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Czujnik DHT22 w salonie",
                            IsActive = true,
                            Name = "Sensor wilgotności - Salon",
                            SeriesId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApiKey = "PRESS_OUT_KEY",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Czujnik BMP180 na balkonie",
                            IsActive = true,
                            Name = "Sensor ciśnienia - Balkon",
                            SeriesId = 3
                        },
                        new
                        {
                            Id = 4,
                            ApiKey = "LIGHT_OFFICE_KEY",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Czujnik LDR w biurze",
                            IsActive = true,
                            Name = "Sensor światła - Biuro",
                            SeriesId = 4
                        },
                        new
                        {
                            Id = 5,
                            ApiKey = "CO2_KITCHEN_KEY",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Czujnik MH-Z19B w kuchni",
                            IsActive = true,
                            Name = "Sensor CO2 - Kuchnia",
                            SeriesId = 5
                        });
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pomiar temperatury w pomieszczeniach",
                            Icon = "thermometer",
                            IsActive = true,
                            MaxValue = 50.0,
                            MinValue = -10.0,
                            Name = "Temperatura pokojowa",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pomiar wilgotności względnej",
                            Icon = "droplet",
                            IsActive = true,
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "Wilgotność powietrza",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pomiar ciśnienia powietrza",
                            Icon = "gauge",
                            IsActive = true,
                            MaxValue = 1050.0,
                            MinValue = 950.0,
                            Name = "Ciśnienie atmosferyczne",
                            Unit = "hPa"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FBBF24",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pomiar jasności otoczenia",
                            Icon = "sun",
                            IsActive = true,
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "Natężenie światła",
                            Unit = "lx"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pomiar dwutlenku węgla w powietrzu",
                            Icon = "cloud",
                            IsActive = true,
                            MaxValue = 2000.0,
                            MinValue = 300.0,
                            Name = "Stężenie CO₂",
                            Unit = "ppm"
                        });
                });

            modelBuilder.Entity("DataPresenter.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$zA2MzBfG5URvZ7.RZoP9.O3UQprC5ZBlhz6ZcY5aJrk0Gq2a4u0yW",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jan.kowalski@example.com",
                            PasswordHash = "$2a$11$testhash000000000000000000000000000000000000000000000000",
                            Username = "jan_kowalski"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anna.nowak@example.com",
                            PasswordHash = "$2a$11$testhash111111111111111111111111111111111111111111111111",
                            Username = "anna_nowak"
                        });
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Measurement", b =>
                {
                    b.HasOne("DataPresenter.Server.Models.Sensor", "Sensor")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataPresenter.Server.Models.Series", "Series")
                        .WithMany("Measurements")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataPresenter.Server.Models.User", "User")
                        .WithMany("Measurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sensor");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Sensor", b =>
                {
                    b.HasOne("DataPresenter.Server.Models.Series", "Series")
                        .WithMany("Sensors")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Sensor", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("DataPresenter.Server.Models.Series", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("DataPresenter.Server.Models.User", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
